---
- name: Create/update setting file
  ansible.builtin.template:
    src: minio.j2
    dest: /erc/minio/minio.conf
    mode: "0644"
- name: Add/update option setting
  ansible.builtin.lineinfile:
    path: /etc/minio/minio.conf
    regexp: "^(#\\s+)?option_name="
    line: option_name=option_value
- name: Add/update custom setting
  ansible.builtin.blockinfile:
    path: /etc/minio/minio.conf
    block: "{{ role_extra_cfg }}"
