---
- name: restart minio
  ansible.builtin.systemd:
    daemon_reload: true
    state: restarted
    name: minio
- name: reload minio
  ansible.builtin.systemd:
    daemon_reload: true
    state: reloaded
    name: minio
