---
- name: Restart minio
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: restarted
    name: minio
- name: Reload minio
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: reloaded
    name: minio
