---
- name: Service minio is active and enabled on system startup
  ansible.builtin.systemd_service:
    name: minio
    state: started
    enabled: true
- name: Allow MinIO web port
  community.general.ufw:
    rule: allow
    port: "{{ minio_address_port }}"
  when: not minio_address_host or minio_address_host in ['localhost', '127.0.0.1', '0.0.0.0']
- name: Allow MinIO console port
  community.general.ufw:
    rule: allow
    port: "{{ minio_console_address_port }}"
  when: not minio_console_address_host or minio_console_address_host in ['localhost', '127.0.0.1', '0.0.0.0']
