---
- name: Get MinIO latest version
  when: minio_version == 'latest'
  block:
    - name: Set Github API request header
      ansible.builtin.set_fact:
        github_api_request_headers:
          Accept: application/vnd.github+json
    - name: Merge Github API Authorization request header
      ansible.builtin.set_fact:
        github_api_request_headers: "{{ github_api_request_headers | combine(merge_request_header) }}"
      vars:
        merge_request_header:
          Authorization: Bearer {{ lookup('env', 'GITHUB_TOKEN') }}
      when: lookup('env', 'GITHUB_TOKEN') | length > 0
    - name: Get latest release
      ansible.builtin.uri:
        url: https://api.github.com/repos/minio/minio/releases/latest
        headers: "{{ github_api_request_headers }}"
      register: latest_releases
    - name: Set minio_version variable
      ansible.builtin.set_fact:
        minio_version: "{{ latest_releases.json.tag_name[8:-1] | regex_replace('(-|T)', '') }}"
- name: Set variables
  ansible.builtin.set_fact:
    minio_download_directory: "{{ ansible_facts['system'] | lower }}-{{ arch_type_maps[ansible_facts['architecture']] }}"
  vars:
    arch_type_maps:
      x86_64: amd64
      aarch64: arm64
- name: Install MinIO packages
  ansible.builtin.apt:
    deb: https://dl.min.io/server/minio/release/{{ minio_download_directory }}/minio.deb
  notify: Restart minio
- name: Install MinIO Client
  ansible.builtin.apt:
    deb: https://dl.min.io/client/mc/release/{{ minio_download_directory }}/mc.deb
