---
- name: Get MinIO latest version
  when: minio_version == 'latest'
  block:
    - name: Get latest release
      ansible.builtin.uri:
        url: https://api.github.com/repos/minio/minio/releases/latest
        headers:
          Accept: application/vnd.github+json
      register: latest_releases
    - name: Set tbls_version variable
      ansible.builtin.set_fact:
        minio_version: "{{ latest_releases.json.tag_name[8:-1] | regex_replace('(-|T)', '') }}"
- name: Set variables
  ansible.builtin.set_fact:
    minio_download_directory: "{{ ansible_facts['system'] | lower }}-{{ architecture_files[ansible_facts['architecture']] }}"
    minio_download_file: minio_{{ minio_version }}.0.0_{{ architecture_files[ansible_facts['architecture']] }}.deb
  vars:
    architecture_files:
      x86_64: amd64
- name: Install MinIO packages
  ansible.builtin.apt:
    deb: https://dl.min.io/server/minio/release/{{ minio_download_directory }}/archive/{{ minio_download_file }}
  notify: restart minio
- name: Install the MinIO Client
  ansible.builtin.get_url:
    url: https://dl.min.io/client/mc/release/{{ minio_download_directory }}/mc
    dest: /usr/local/bin/mc
    mode: "0755"
